// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    content_id,
    content_url,
    extractor_id,
    caption,
    nsfw
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) ON CONFLICT (content_id, extractor_id) DO UPDATE SET
    caption = EXCLUDED.caption,
    content_url = EXCLUDED.content_url,
    nsfw = EXCLUDED.nsfw,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type CreateMediaParams struct {
	ContentID   string
	ContentUrl  string
	ExtractorID string
	Caption     pgtype.Text
	Nsfw        bool
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.ContentID,
		arg.ContentUrl,
		arg.ExtractorID,
		arg.Caption,
		arg.Nsfw,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMediaFormat = `-- name: CreateMediaFormat :exec
INSERT INTO media_format (
    format_id,
    item_id,
    file_id,
    type,
    audio_codec,
    video_codec,
    duration,
    file_size,
    title,
    artist,
    width,
    height,
    bitrate
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
`

type CreateMediaFormatParams struct {
	FormatID   string
	ItemID     int64
	FileID     string
	Type       MediaType
	AudioCodec NullMediaCodec
	VideoCodec NullMediaCodec
	Duration   pgtype.Int4
	FileSize   pgtype.Int8
	Title      pgtype.Text
	Artist     pgtype.Text
	Width      pgtype.Int4
	Height     pgtype.Int4
	Bitrate    pgtype.Int8
}

func (q *Queries) CreateMediaFormat(ctx context.Context, arg CreateMediaFormatParams) error {
	_, err := q.db.Exec(ctx, createMediaFormat,
		arg.FormatID,
		arg.ItemID,
		arg.FileID,
		arg.Type,
		arg.AudioCodec,
		arg.VideoCodec,
		arg.Duration,
		arg.FileSize,
		arg.Title,
		arg.Artist,
		arg.Width,
		arg.Height,
		arg.Bitrate,
	)
	return err
}

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO media_item (
    media_id
) VALUES (
    $1
) RETURNING id
`

func (q *Queries) CreateMediaItem(ctx context.Context, mediaID int64) (int64, error) {
	row := q.db.QueryRow(ctx, createMediaItem, mediaID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMedia = `-- name: GetMedia :one
SELECT 
    id,
    content_id,
    content_url,
    extractor_id,
    caption,
    nsfw
FROM media WHERE id = $1
`

type GetMediaRow struct {
	ID          int64
	ContentID   string
	ContentUrl  string
	ExtractorID string
	Caption     pgtype.Text
	Nsfw        bool
}

func (q *Queries) GetMedia(ctx context.Context, id int64) (GetMediaRow, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i GetMediaRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ContentUrl,
		&i.ExtractorID,
		&i.Caption,
		&i.Nsfw,
	)
	return i, err
}

const getMediaByContentID = `-- name: GetMediaByContentID :one
SELECT 
    id,
    content_id,
    content_url,
    extractor_id,
    caption,
    nsfw
FROM media WHERE content_id = $1
AND extractor_id = $2
`

type GetMediaByContentIDParams struct {
	ContentID   string
	ExtractorID string
}

type GetMediaByContentIDRow struct {
	ID          int64
	ContentID   string
	ContentUrl  string
	ExtractorID string
	Caption     pgtype.Text
	Nsfw        bool
}

func (q *Queries) GetMediaByContentID(ctx context.Context, arg GetMediaByContentIDParams) (GetMediaByContentIDRow, error) {
	row := q.db.QueryRow(ctx, getMediaByContentID, arg.ContentID, arg.ExtractorID)
	var i GetMediaByContentIDRow
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.ContentUrl,
		&i.ExtractorID,
		&i.Caption,
		&i.Nsfw,
	)
	return i, err
}

const getMediaFormat = `-- name: GetMediaFormat :one
SELECT 
    format_id,
    item_id,
    file_id,
    type,
    audio_codec,
    video_codec,
    duration,
    file_size,
    title,
    artist,
    width,
    height,
    bitrate
FROM media_format WHERE item_id = $1
`

type GetMediaFormatRow struct {
	FormatID   string
	ItemID     int64
	FileID     string
	Type       MediaType
	AudioCodec NullMediaCodec
	VideoCodec NullMediaCodec
	Duration   pgtype.Int4
	FileSize   pgtype.Int8
	Title      pgtype.Text
	Artist     pgtype.Text
	Width      pgtype.Int4
	Height     pgtype.Int4
	Bitrate    pgtype.Int8
}

func (q *Queries) GetMediaFormat(ctx context.Context, itemID int64) (GetMediaFormatRow, error) {
	row := q.db.QueryRow(ctx, getMediaFormat, itemID)
	var i GetMediaFormatRow
	err := row.Scan(
		&i.FormatID,
		&i.ItemID,
		&i.FileID,
		&i.Type,
		&i.AudioCodec,
		&i.VideoCodec,
		&i.Duration,
		&i.FileSize,
		&i.Title,
		&i.Artist,
		&i.Width,
		&i.Height,
		&i.Bitrate,
	)
	return i, err
}

const getMediaItems = `-- name: GetMediaItems :many
SELECT 
    id,
    media_id
FROM media_item WHERE media_id = $1
`

type GetMediaItemsRow struct {
	ID      int64
	MediaID int64
}

func (q *Queries) GetMediaItems(ctx context.Context, mediaID int64) ([]GetMediaItemsRow, error) {
	rows, err := q.db.Query(ctx, getMediaItems, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsRow
	for rows.Next() {
		var i GetMediaItemsRow
		if err := rows.Scan(&i.ID, &i.MediaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}


const deleteMediaByContentID = `-- name: DeleteMediaByContentID :exec
DELETE FROM media WHERE content_id = $1 AND extractor_id = $2
`

type DeleteMediaByContentIDParams struct {
	ContentID   string
	ExtractorID string
}

func (q *Queries) DeleteMediaByContentID(ctx context.Context, arg DeleteMediaByContentIDParams) error {
	_, err := q.db.Exec(ctx, deleteMediaByContentID, arg.ContentID, arg.ExtractorID)
	return err
}


const deleteMediaItemsByMediaID = `-- name: DeleteMediaItemsByMediaID :exec
DELETE FROM media_item WHERE media_id = $1
`

func (q *Queries) DeleteMediaItemsByMediaID(ctx context.Context, mediaID int64) error {
	_, err := q.db.Exec(ctx, deleteMediaItemsByMediaID, mediaID)
	return err
}

const getMediaItemsWithFormats = `-- name: GetMediaItemsWithFormats :many
SELECT
    mi.id as item_id,
    mf.format_id,
    mf.item_id,
    mf.file_id,
    mf.type,
    mf.audio_codec,
    mf.video_codec,
    mf.duration,
    mf.file_size,
    mf.title,
    mf.artist,
    mf.width,
    mf.height,
    mf.bitrate
FROM media_item mi
JOIN media_format mf ON mf.item_id = mi.id
WHERE mi.media_id = $1
ORDER BY mi.id
`

type GetMediaItemsWithFormatsRow struct {
	ItemID     int64
	FormatID   string
	ItemID_2   int64
	FileID     string
	Type       MediaType
	AudioCodec NullMediaCodec
	VideoCodec NullMediaCodec
	Duration   pgtype.Int4
	FileSize   pgtype.Int8
	Title      pgtype.Text
	Artist     pgtype.Text
	Width      pgtype.Int4
	Height     pgtype.Int4
	Bitrate    pgtype.Int8
}

func (q *Queries) GetMediaItemsWithFormats(ctx context.Context, mediaID int64) ([]GetMediaItemsWithFormatsRow, error) {
	rows, err := q.db.Query(ctx, getMediaItemsWithFormats, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsWithFormatsRow
	for rows.Next() {
		var i GetMediaItemsWithFormatsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.FormatID,
			&i.ItemID_2,
			&i.FileID,
			&i.Type,
			&i.AudioCodec,
			&i.VideoCodec,
			&i.Duration,
			&i.FileSize,
			&i.Title,
			&i.Artist,
			&i.Width,
			&i.Height,
			&i.Bitrate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
